"""
Stage 6 -- turn a nanoGPT checkpoint into a `.gptc` file for the board.

    python -m chessgpt.export --ckpt ../nanoGPT/out-chess-small/ckpt.pt \
        --out out/chess-small.gptc --emit-header

`--emit-header` also writes a C header with the config and every tensor's byte
offset, so runtime/ can mmap the blob without a JSON parser.
"""

import argparse
import os

import numpy as np

from . import gptc


def state_dict_to_tensors(sd):
    """nanoGPT state_dict -> .gptc tensor names (strip `transformer.`,
    drop the lm_head copy since it is tied to wte)."""
    out = {}
    for k, v in sd.items():
        if k.startswith('_orig_mod.'):
            k = k[len('_orig_mod.'):]
        if k == 'lm_head.weight':
            continue
        if k.startswith('transformer.'):
            k = k[len('transformer.'):]
        k = k.replace('wte.weight', 'wte').replace('wpe.weight', 'wpe')
        out[k] = v.detach().float().cpu().numpy()
    return out


def emit_header(path, config, directory):
    lines = [
        '/* generated by chessgpt.export -- do not edit */',
        '#ifndef GPTC_MODEL_H',
        '#define GPTC_MODEL_H',
        '',
    ]
    for k in ('n_layer', 'n_head', 'n_embd', 'block_size', 'vocab_size'):
        lines.append(f'#define GPTC_{k.upper()} {config[k]}')
    lines.append(f'#define GPTC_BIAS {1 if config["bias"] else 0}')
    lines.append(f'#define GPTC_N_TENSORS {len(directory)}')
    lines.append('')
    lines.append('/* name, dtype, offset, nbytes, scale_offset (-1 if fp32) */')
    lines.append('#define GPTC_TENSOR_TABLE \\')
    rows = []
    for e in directory:
        rows.append('  X("{name}", {dt}, {off}UL, {nb}UL, {so}L)'.format(
            name=e['name'], dt=0 if e['dtype'] == 'fp32' else 1,
            off=e['offset'], nb=e['nbytes'], so=e.get('scale_offset', -1)))
    lines.append(' \\\n'.join(rows))
    lines.append('')
    lines.append('#endif /* GPTC_MODEL_H */')
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def main(argv=None):
    p = argparse.ArgumentParser(description='export a nanoGPT ckpt to .gptc')
    p.add_argument('--ckpt', required=True)
    p.add_argument('--out', required=True)
    p.add_argument('--fp32', action='store_true', help='skip int8 quantization')
    p.add_argument('--emit-header', action='store_true',
                   help='also write <out>.h for the C runtime')
    p.add_argument('--block-size', type=int, default=0,
                   help='shrink the exported context (trims wpe and KV cache)')
    args = p.parse_args(argv)

    import torch
    ckpt = torch.load(args.ckpt, map_location='cpu', weights_only=False)
    ma = ckpt['model_args']
    tensors = state_dict_to_tensors(ckpt['model'])

    block_size = args.block_size or ma['block_size']
    if block_size > ma['block_size']:
        raise SystemExit(f'--block-size {block_size} exceeds trained {ma["block_size"]}')
    if block_size < ma['block_size']:
        tensors['wpe'] = tensors['wpe'][:block_size]

    config = {
        'n_layer': ma['n_layer'], 'n_head': ma['n_head'], 'n_embd': ma['n_embd'],
        'block_size': block_size, 'vocab_size': ma['vocab_size'],
        'bias': bool(ma['bias']), 'tokenizer': 'square_pair_uci_v1',
        'iter_num': int(ckpt.get('iter_num', 0)),
        'val_loss': float(ckpt.get('best_val_loss', float('nan'))),
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or '.', exist_ok=True)
    size = gptc.write(args.out, config, tensors, quant=not args.fp32)

    n_params = sum(v.size for k, v in tensors.items() if k != 'wpe')
    print(f'{args.out}')
    print(f'  params (non-embedding-pos) : {n_params/1e6:.2f}M')
    print(f'  quantization               : {"fp32" if args.fp32 else "int8 rows"}')
    print(f'  block_size                 : {block_size}')
    print(f'  file size                  : {size/1e6:.2f} MB')
    kv = 2 * config['n_layer'] * config['n_head'] * block_size * \
        (config['n_embd'] // config['n_head']) * 4
    print(f'  fp32 KV cache at full ctx  : {kv/1e6:.2f} MB')

    if args.emit_header:
        _, _, directory = gptc.read(args.out, dequantize=False)
        hp = os.path.splitext(args.out)[0] + '.h'
        emit_header(hp, config, directory)
        print(f'  header                     : {hp}')


if __name__ == '__main__':
    main()
